version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          PGUSER: root
      - image: circleci/postgres:10.5-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: laa-great-ideas_test

    working_directory: ~/repo

    steps:
      - checkout
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: npm install
      - run: bundle exec rake db:create db:schema:load
      - run: bundle exec rubocop
      - run: bundle exec rspec
